server:
  port: 8080
spring:
  application:
    name: news
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  thymeleaf:
    cache: false

  rabbitmq:
    host: 110.43.48.124
    port: 5672
    username: admin
    password: admin
    virtual-host: news_host
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 500
        auto-startup: true
        default-requeue-rejected: true
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 1.0

mybatis:
  type-aliases-package: com.sz.news.model.*
  mapper-locations: classpath:mappers/*Mapper.xml

logging:
  level:
    com.sz.news.dao: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
#        include: shutdown,health,info,env,beans,conditions